version: '3'
services: 
    server:
        restart: always
        build: backend
        ports: 
            - 9000:9000
    frontend:
        restart: always
        build: frontend
        ports: 
            - 3000:3000
        depends_on: 
            - server
        stdin_open: true
        container_name: frontend