export default {
  card: { marginRight: "auto", marginLeft: "auto", width: "80%" },
  cardheadermeta: { marginTop: ".5rem" },
  butttongroup: {
    position: "absolute",
    right: ".4rem",
    top: ".4rem",
    width: "14rem",
    height: "3rem",
  },
  editbutton: { width: "3.5rem", marginRight: ".5rem" },
  marginright: {
    marginRight: ".5rem",
  },
  privatebutton: {
    width: "4rem",
    padding: ".4rem",
  },
  width4rem: { width: "4rem",padding:".5rem" },
  marginTop: { marginTop: "2rem" },
  cardcontent: { padding: ".5rem" },
  carda: { marginRight: ".5rem" },
  cardicon: { color: "red" },
  cardbutton: { marginLeft: "1.5rem" },
  margintop: { marginTop: ".5rem" },
  publicprofilegrid: { padding: "1.5rem" },
  publicprofilecard: {
    widht: "20rem",
    marginRight: "auto",
    marginLeft: "auto",
  },
  publicprofilecardheader: { marginTop: "1rem", fontSize: "1.1rem" },
  publicprofilecontainer: { marginBottom: "1rem" },
  cardcontainer: { marginTop: ".5rem", padding: ".3rem" },
  bluespan: { color: "blue" },
};
